import type { Metadata } from "next";
import Header from "./_components/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="grid grid-rows-[auto,1fr] min-h-screen">
      <Header />
      {children}
    </div>
  );
}
